name 'mklauber-aide'
version '0.5.0'
author 'Matthew Lauber'
license 'Apache Version 2.0'
source 'https://github.com/mklauber/aide'
project_page 'https://github.com/mklauber/aide'
summary 'A puppet module for installing and configuring aide'
description ''
dependency 'puppetlabs-concat', '>=1.0.0'
dependency 'puppetlabs-stdlib', '>=3.0.0'
