name 'mklauber-aide'
version '1.1.0'
author 'Matthew Lauber'
license 'Apache Version 2.0'
source 'https://github.com/mklauber/aide'
project_page 'https://github.com/mklauber/aide'
summary 'A puppet module for installing and configuring aide'
description 'A puppet module for setting up and configuring aide (Advanced Intrusion Detection System) via puppet.'
dependency 'puppetlabs-concat', '>=1.0.0'
dependency 'puppetlabs-stdlib', '>=3.0.0'
